# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

#pod的工程不显示任何警告
inhibit_all_warnings!

target 'mylesson' do

end

target 'mylessonTests' do

end

target 'mylessonUITests' do

end

